### PR TITLE
New /sent_deps/ endpoint, fix unit tests, add some optional tokenizer config

### PR DESCRIPTION
**Pull request by matthewarmand**
- Adds a new endpoint which combines functionality of two existing; splits into sentences and then tokenizes into dependencies. Adds documentation for this as well.
- Fixes the existing unit tests, adds documentation on how to run them.
- Adds a way to optionally configure some basic [tokenization special cases](https://spacy.io/usage/linguistic-features#special-cases) with an environment variable. For example, keeping contractions intact

### CODE REVIEW

**Comment by jgontrum** [comment]
Looks amazing! I’ll give it a try tomorrow

**Comment by matthewarmand** [comment]
Sounds good @jgontrum, let me know if you'd like any extra context on anything, or if anything doesn't make sense or should be different.

**Comment by jgontrum** [comment]
Looks good so far! One thing I've noticed is that the server returns a 500 if the model in the request is not found. Could you please catch it and return a more informative message as we do with the `/dep` endpoint?:

```json
{
  "title": "Dependency parsing failed",
  "description": "[E050] Can't find model 'some_unknown_model'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory."
}
```

**Comment by matthewarmand** [comment]
> Looks good so far! One thing I've noticed is that the server returns a 500 if the model in the request is not found. Could you please catch it and return a more informative message as we do with the `/dep` endpoint?:

Good catch, yes I can definitely make that change. I notice that a couple of the other endpoints are missing that error handling as well; while I'm in here would you like me to add that to `/sents` and `/ents`?

Additionally, `/models` and `/version` are just returning a 500; if you'd like I can expand that to something a bit more informative, such as:
```python
except Exception as e:
    raise falcon.HTTPInternalServerError(
        'Error occurred retrieving models',
        '{}'.format(e))
```

**Comment by matthewarmand** [comment]
@jgontrum check out [4c64c74](https://github.com/jgontrum/spacy-api-docker/pull/33/commits/4c64c746bc55924547f64b4c499e0d0b4adabb95) for code addressing your feedback.

I added the handling to the new `/sents_dep` endpoint as you requested, and also added similar handling to `/ent` and `/sents`, which were also missing that. I also wrote a parametrized unit test case to cover that behavior for all those endpoints.

I also went ahead and added better 500 handling to `/version` and `/models` so a message about what went wrong will be returned.

**Comment by jgontrum** [comment]
Looks good to me :) Thank you for work!

**Pull request merged**
